config/routes.rb
Rails.application.routes.draw do
  #root to:  'chats#show'
  
  root to: 'pages#home'
  mount ActionCable.server => '/cable'

  get '/chat', to: 'chats#show'
  
  get 'signup', to: 'users#new'
  resources :users, except: [:new]

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/message.rb
class Message < ApplicationRecord
    after_create_commit { ChatBroadcastJob.perform_later self }
    
    belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :messages, dependent: :destroy
	before_save { self.email = email.downcase }

	validates :name, presence: true, 
						uniqueness: { case_sensitive: false }, 
						length: { minimum: 3, maximum: 20 }
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
	validates :email, presence: true, length: { maximum: 105 },
						uniqueness: { case_sensitive: false },
						format: { with: VALID_EMAIL_REGEX }

	has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :current_user, :logged_in?

  def current_user
  	@current_user ||=	User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
  	!!current_user
  end

  def require_user
  	if !logged_in?
  		flash[:danger] = "You must be logged in to perform that action"
  		redirect_to root_path
  	end
  end

end

app/controllers/chats_controller.rb
class ChatsController < ApplicationController
  def show
    if logged_in?
      @messages = Message.all
    else
      redirect_to root_path
      flash[:danger] = "You must be logged to enter the chat room"
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def home
  	redirect_to chat_path if logged_in?
  end

  def about

  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

	def new

	end

	def create
		user = User.find_by(email: params[:session][:email].downcase)
		if user && user.authenticate(params[:session][:password])
			session[:user_id] = user.id
			flash[:success] = "You have successfully logged in"
			redirect_to root_path
		else
			flash.now[:danger] = "There was something worng with your login information"
			render 'new'
		end
	end

	def destroy
		session[:user_id] = nil
		flash[:success] = "You have logged out"
		redirect_to root_path
	end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :set_user, only:[:edit, :update, :show]
	before_action :require_same_user, only: [:edit, :update, :destroy]
	before_action :require_admin, only: [:destroy]

	def index
	end

	def new
		@user = User.new
	end

	def create
		@user = User.new(user_params)
		if @user.save
			session[:user_id] = @user.id
			flash[:success] = "Welcome to the Arcane Refuge, #{@user.name}!"
			redirect_to root_path
		else
			render 'new'
		end
	end

	def edit
	end

	def update
		if @user.update(user_params)
			flash[:success] = "Your account was updated successfully!"
			redirect_to user_path(@user)
		else
			render 'edit'
		end				
	end

	def show
	end

	def destroy
		@user = User.find(params[:id])
		@user.destroy
		flash[:danger] = "User and all his messages have been deleted"
		redirect_to users_path
	end


	private
	def user_params
		params.require(:user).permit(:name, :email, :password)
	end
	def set_user
		@user = User.find(params[:id])
	end
	def require_same_user
		if current_user != @user and !current_user.admin?	
			flash[:danger] = "You can only edit your own account"
			redirect_to root_path
		end
	end
	def require_admin
		if logged_in? and !current_user.admin?
			flash[:danger] = "Only admin users can perform that action"
			redirect_to root_path
		end
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chats_helper.rb
module ChatsHelper
end

app/views/chats/show.html.erb
<div align="center" class="container">
  <h1 class="title">Chat</h1>
  <div id="messages">
    <%= render @messages %>
  </div>

  <form>
    <% if logged_in? %>
      <%= hidden_field_tag :user, current_user.id, :id => "user" %>
    <% end %>
    <input type="text" id="speaker" data-behavior="chat_speaker" placeholder="Type your message here and press [Enter]">
  </form>
</div>

<script>
  $("#messages").scrollTop($("#messages")[0].scrollHeight);
  $(document).ready(function(){
      $('[data-toggle="tooltip"]').tooltip();
  });
</script>

app/views/layouts/_alerts.html.erb
<div class="row">
	<div class="col-xs-10 col-xs-offset-1">
		<% flash.each do |name, msg| %>
			<div class='alert alert-<%= "#{name}" %>'>
				<a href="#" class="close" data-dismiss="alert">&#215;</a>
				<%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>
			</div>
		<% end %>
	</div>
</div>

app/views/layouts/_footer.html.erb
<footer class="footer">
	<small style="margin-left: 20px;">
		<!-- Coypright &copy; <a href="https://www.udemy.com" target="_blank">The Complete Ruby On Rails Developer</a>
		by <a href="https://gitlab.com/diegoliveiras" target="_blank">Diego Oliveira</a> -->
	</small>
	<nav style="margin-right: 20px;">
		<ul> 
			<li>The Arcane Refuge 
			by <a href="https://gitlab.com/diegoliveiras" target="_blank">Diego Oliveira</a></li>
		</ul>
	</nav>
</footer>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-default" id="main-navbar">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Arcane Refuge", root_path, class:"navbar-brand", id:"logo" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        
      </ul>
      <form class="navbar-form navbar-left">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
      <ul class="nav navbar-nav navbar-right">
        <% if logged_in? %>
          <li><%= link_to 'Log Out', logout_path, method: :delete %></li>
          <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Your Profile <%= "Admin" if current_user.admin? %><span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to "Edit your profile", edit_user_path(current_user) %></li>
            <li><%= link_to "View your profile", user_path(current_user) %></li>
          </ul>
        </li>
        <% else %>
          <li><%= link_to 'Log In', login_path %></li>
          <li><%= link_to 'Sign Up', signup_path %></li>
        <% end %>
        
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Arcane Refuge</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navigation' %>
    
    <div class="container">

      <%= render 'layouts/alerts' %>
      <%= yield %>
      
      
    </div>
    
  </body>
  <%= render 'layouts/footer' %>
</html>

app/views/messages/_message.html.erb
<div class="message">
  <p>
    <spam data-toggle="tooltip" title=<%= message.created_at %>>
      <strong><%= message.user.name%>:</strong> <%= message.content %>
    </spam>
  </p>
</div>

app/views/pages/home.html.erb
<div class="center jumbotron">
	<h2>The Arcane Refuge</h2>
	<h3>Online Chatting</h3>

	<div class="wrap" align="center">
		<%= link_to "Sign up now", "signup", class: "button" %>
	</div>

</div>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
	<div class="row">
		<div class="col-xs-8 col-xs-offset-2">
			<div class="panel panel-danger">
				<div class="panel-heading">
					<h2 class="panel-title">
						<%= pluralize(obj.errors.count, "error") %>
						prohibited this article from being saved:
					</h2>
					<div class="panel-body">
						<ul>
							<% obj.errors.full_messages.each do |msg| %>
							<li><%= msg %></li>
							<% end %>
						</ul>
					</div>
				</div>
			</div>
		</div>
	</div>
<% end %>

app/views/users/_form.html.erb
<%= render 'shared/errors', obj: @user %>

<div class="row">
	<div class="col-xs-12"> 
		<%= form_for(@user, :html => {class: "form-horizontal", role: "form"}) do |f| %>
			<div class="form-group">
				<div class="control-label col-sm-2">
					<%= f.label :name %>
				</div>
				<div class="col-sm-8">
					<%= f.text_field  :name, class: "form-control", placeholder: "Enter username", autofocus: true %>
				</div>
			</div>
			<div class="form-group">
				<div class="control-label col-sm-2">
					<%= f.label :email %>
				</div>
				<div class="col-sm-8">
					<%= f.text_field  :email, class: "form-control", placeholder: "Enter email" %>					
				</div>
			</div>
			<div class="form-group">
				<div class="control-label col-sm-2">
					<%= f.label :password %>
				</div>
				<div class="col-sm-8">
					<%= f.password_field  :password, class: "form-control", placeholder: "Enter password" %>
				</div>
			</div>
			<div class="form-group">
				<div class="col-sm-offset-2 col-sm-10">
					<%= f.submit(@user.new_record? ? "Sign up" : "Update my account", 
							class: 'btn btn-primary btn-lg') %>
				</div>
			</div>
		<% end %>

	</div>
</div>

app/views/users/new.html.erb
<h1 align="center">SignUp and Start Chatting</h1>

<%= render 'form' %>